config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "users/unsubscribe" => "users#unsubscribe"
    patch "users/withdraw" => "users#withdraw"
    get '/search', to: 'searches#search'
    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :logs, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :log_comments, only: [:create, :destroy]
    end
  end
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :logs, only: [:index, :show, :destroy]
  end
  
end

app/models/log.rb
class Log < ApplicationRecord

  belongs_to :user
  has_many :log_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :log_tags, dependent: :destroy
  has_many :tags, through: :log_tags

  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true
  validates :location, presence: true
  validates :date, presence: true
  validates :price, presence: true
  validates :public_order, presence: true
  validates :meal, presence: true

  enum price: { too_expensive: 0, expensive: 1, ordinarily_price: 2, cheep: 3, too_cheep: 4 }
  enum public_order: { great_public: 0, good_public: 1, ordinarily_public: 2, bad_public: 3, worst_public: 4 }
  enum meal: { great_meal: 0, good_meal: 1, ordinarily_meal: 2, bad_meal: 3, worst_meal: 4 }

  def get_image
    image.variant(resize_to_limit: [500, 500]).processed
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tags(savelog_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - savelog_tags
    new_tags = savelog_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    new_tags.each do |new_name|
      log_tag = Tag.find_or_create_by(name:new_name)
      self.tags << log_tag
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Log.where(title: content)
    elsif method == 'forward'
      Log.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Log.where('title LIKE ?', '%'+content)
    else
      Log.where('title LIKE ?', '%'+content+'%')
    end
  end

end

app/controllers/admin/logs_controller.rb
class Admin::LogsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @logs = Log.page(params[:page])
  end

  def show
    @log = Log.find(params[:id])
    unless @log
      redirect_to admin_logs_path, alert: 'ログが見つかりませんでした'
    end
  end

  def destroy
    @log = Log.find_by(id: params[:id])
    unless @log
      redirect_to logs_path, alert: 'ログが見つかりませんでした'
    end
    @log.destroy
    redirect_to admin_logs_path, notice: 'ログが削除されました'
  end

  private

  def log_params
    params.require(:log).permit(:title, :body, :location, :date, :price, :public_order, :meal, :image)
  end
  
end

app/helpers/admin/logs_helper.rb
module Admin::LogsHelper
end

app/views/admin/logs/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12">
    <h4 class="font-weight-bold text-center bg-light py-2">ログ一覧</h4>
    </div>
  </div>

  <div class="row">
    <div class="col text-center mb-4">
      <%= link_to "新しい順", logs_path(sort: 'created_at DESC'), class: "btn btn-outline-primary mx-2" %>
      <%= link_to "評価の高い順", logs_path(sort: 'rate DESC'), class: "btn btn-outline-primary mx-2" %>
    </div>
  </div>

  <div class="row">
    <div class="col">

      <table class='table table-bordered table-hover mx-auto'>
        <thead class="thead-dark">
          <tr>
            <th>ログID</th>
            <th>タイトル</th>
            <th>タグ</th>
            <th>旅行先</th>
            <th>投稿者</th>
            <th>コメント</th>
            <th>いいね</th>
            <th>評価</th>
          </tr>
        </thead>

        <tbody>
          <% @logs.each do |log| %>
            <tr>
              <td><%= log.id %></td>
              <td><%= link_to log.title, admin_log_path(log.id), class: "text-primary" %></td>
              <td>
                <ul class="list-unstyled mb-0">
                  <% log.tags.each do |tag| %>
                    <li><span class="badge badge-secondary"><%= tag.name %></span></li>
                  <% end %>
                </ul>
              </td>
              <td><%= log.location %></td>
              <td><%= link_to log.user.name, admin_user_path(log.user.id), class: "text-success" %></td>
              <td><%= link_to "#{log.log_comments.count} コメント", admin_log_path(log.id), class: "text-info" %></td>
              <td><%= link_to "#{log.favorites.count} いいね", admin_log_path(log.id), class: "text-danger" %></td>
              <td><%= render "public/logs/static_rate", log: log %></td>
            </tr>
          <% end %>
        </tbody>

      </table>

      <!-- ページネーション -->
      <div class="d-flex justify-content-center">
        <%= paginate @logs, class: "pagination pagination-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/logs/show.html.erb
<div class="container my-5">
  <div class="row mb-4">
    <div class="col">
    <h4 class="font-weight-bold text-center bg-light py-2">ログ詳細</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4 text-center mb-4">
      <% if @log.image.attached? %>
        <%= image_tag @log.get_image, class: "img-fluid rounded" %>
      <% else %>
        <%= image_tag asset_path('no_image.jpg'), size: "200x200", class: "img-fluid rounded" %>
      <% end %>
    </div>

    <div class="col-lg-8">
      <table class="table table-bordered table-hover">
        <tbody>
          <tr>
            <th>ログID</th>
            <td><%= @log.id %></td>
          </tr>
          <tr>
            <th>タイトル</th>
            <td><%= @log.title %></td>
          </tr>
          <tr>
            <th>タグ</th>
            <td><%= @log.tags.map(&:name).join(', ') if @log.tags.any? %></td>
          </tr>
          <tr>
            <th>旅行先</th>
            <td><%= @log.location %></td>
          </tr>
          <tr>
            <th>旅行日</th>
            <td><%= @log.date %></td>
          </tr>
          <tr>
            <th>物価</th>
            <td><%= @log.price_i18n %></td>
          </tr>
          <tr>
            <th>治安</th>
            <td><%= @log.public_order_i18n %></td>
          </tr>
          <tr>
            <th>食事</th>
            <td><%= @log.meal_i18n %></td>
          </tr>
          <tr>
            <th>投稿者</th>
            <td><%= link_to @log.user.name, admin_user_path(@log.user.id), class: "text-success" %></td>
          </tr>
          <tr>
            <th>内容</th>
            <td><%= @log.body %></td>
          </tr>
          <tr>
            <th>評価</th>
            <td><%= render "public/logs/static_rate", log: @log %></td>
          </tr>
          <tr>
            <th>いいね数</th>
            <td><%= @log.favorites.count %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="text-center my-5">
    <h5><%= @log.log_comments.count %> 件のコメント</h5>
    <% @log.log_comments.each do |log_comment| %>
      <div class="border p-3 mb-2 rounded">
        <p><strong><%= log_comment.user.name %></strong> <span class="text-muted"><%= log_comment.created_at.strftime('%Y/%m/%d') %></span></p>
        <p><%= log_comment.comment %></p>
        <% if log_comment.user == current_user %>
          <%= link_to "削除", log_log_comment_path(log_comment.log, log_comment), method: :delete, class: "text-danger" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="text-center mt-4">
    <%= link_to "削除する", admin_log_path(@log.id), class: "btn btn-danger btn-lg", method: :delete, "data-confirm" => "本当に削除しますか？" %>
  </div>

</div>