config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "users/unsubscribe" => "users#unsubscribe"
    patch "users/withdraw" => "users#withdraw"
    get '/search', to: 'searches#search'
    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :logs, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :log_comments, only: [:create, :destroy]
    end
  end
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :logs, only: [:index, :show, :destroy]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :logs, dependent: :destroy
  has_many :log_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  validates :name, presence: true
  validates :age, presence: true

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def status
    if gender == true
      "男性"
    else
      "女性"
    end
  end

  def is_active_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end

  def active_for_authentication?
    super && (is_active == true)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :prevent_guest_user, only: [:update] 
  
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find_by(id: params[:id])
    unless @user
      redirect_to admin_users_path, alert: "ユーザーが見つかりませんでした"
    end
    @logs = @user.logs
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.email == 'guest@example.com'
      flash[:alert] = 'ゲストユーザーの情報は更新できません'
      redirect_to admin_user_path(@user) and return
    end

    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :gender, :is_active)
  end

  def prevent_guest_user
    user = User.find(params[:id])
    if user.email == 'guest@example.com'
      flash[:alert] = 'ゲストユーザーの情報は更新できません'
      redirect_to admin_user_path(user)  # 更新が禁止されたユーザーの詳細ページにリダイレクト
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
    <h4 class="font-weight-bold text-center bg-light py-2">ユーザー編集</h4>
    </div>
  </div>

  <!-- エラーメッセージ表示 -->
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <strong><%= @user.errors.count %>件のエラーが発生しました</strong>
      <ul class="mt-2">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-8 offset-md-2">

      <%= form_with model: @user, url: admin_user_path(@user.id), class: "bg-light p-4 rounded shadow-sm" do |f| %>

        <div class="form-group">
          <div class="font-weight-bold">ユーザーID</div>
          <div><%= @user.id %></div>
        </div>

        <div class="form-group">
          <%= f.label :name, "名前", class: "font-weight-bold" %>
          <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "名前を入力してください" %>
        </div>

        <div class="form-group">
          <%= f.label :age, "年齢", class: "font-weight-bold" %>
          <%= f.number_field :age, class: "form-control", placeholder: "年齢を入力してください" %>
        </div>

        <div class="form-group">
          <%= f.label :gender, "性別", class: "font-weight-bold" %><br>
          <div class="custom-control custom-radio custom-control-inline">
            <%= f.radio_button :gender, true, id: "gender_male", class: "custom-control-input" %>
            <%= f.label :gender, "男性", class: "custom-control-label", for: "gender_male" %>
          </div>
          <div class="custom-control custom-radio custom-control-inline">
            <%= f.radio_button :gender, false, id: "gender_female", class: "custom-control-input" %>
            <%= f.label :gender, "女性", class: "custom-control-label", for: "gender_female" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :email, "メールアドレス", class: "font-weight-bold" %>
          <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "メールアドレスを入力してください" %>
        </div>

        <div class="form-group">
          <div class="font-weight-bold">会員ステータス </div>
          <div class ="custom-control custom-radio custom-control-inline">
            <%= f.radio_button :is_active, true, checked: @user.is_active == true, class: 'custom-control-input', id: 'is_active_status-active' %>
            <%= f.label :is_active,'有効', class: 'custom-control-label', for: 'is_active_status-active' %>
          </div>
          <div class ="custom-control custom-radio custom-control-inline">
            <%= f.radio_button :is_active, false, checked: @user.is_active == false, class: 'custom-control-input', id: 'is_active_status-deleted' %>
            <%= f.label :is_active,'退会', class: 'custom-control-label', for: 'is_active_status-deleted' %>
          </div>
        </div>



        <div class="d-flex justify-content-center mt-4">
          <%= f.submit '変更を保存', class: "btn btn-success btn-lg px-5 py-3 mr-2" %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container my-5">
  <!-- ヘッダー -->
  <div class="row mb-4">
    <div class="col-12">
      <h4 class="font-weight-bold text-center bg-light py-3 shadow-sm rounded">ユーザー一覧</h4>
    </div>
  </div>

  <!-- ユーザーリスト -->
  <div class="row justify-content-center">
    <div class="col-lg-10 col-md-12">

      <!-- テーブル -->
      <table class="table table-bordered table-hover mx-auto w-100 shadow-sm">
        <thead class="thead-dark">
          <tr>
            <th>会員ID</th>
            <th>名前</th>
            <th>年齢</th>
            <th>性別</th>
            <th>会員ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= link_to user.name, admin_user_path(user.id), class: "text-primary font-weight-bold" %></td>
              <td><%= user.age %>歳</td>
              <td class="<%= user.gender ? 'text-success font-weight-bold' : 'text-muted font-weight-bold' %>"><%= user.gender ? '男性' : '女性' %></td>
              <td class="<%= user.is_active ? 'text-success font-weight-bold' : 'text-muted font-weight-bold' %>"><%= user.is_active ? '有効' : '無効' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <!-- ページネーション -->
      <div class="d-flex justify-content-center mt-4">
        <%= paginate @users, class: "pagination pagination-lg" %>
      </div>
      
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container mt-4">
<div>
  <%= flash[:alert] %>
</div>
  <div class="row">
    <div class="col-12">
      <h4 class="font-weight-bold text-center bg-light py-2">ユーザー詳細</h4>
    </div>
  </div>
  <div class="row my-4">
    <div class="col-lg-4 col-md-6">
      <div class="card p-3 shadow-sm">
        <h5 class="font-weight-bold mb-3">プロフィール</h5>
        <table class="table table-sm">
          <tbody>
            <tr>
              <td><strong>会員ID</strong></td>
              <td><%= @user.id %></td>
            <tr>
              <td><strong>名前</strong></td>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <td><strong>年齢</strong></td>
              <td><%= @user.age %>歳</td>
            </tr>
            <tr>
              <td><strong>性別</strong></td>
              <td class="<%= @user.gender ? 'text-success font-weight-bold' : 'text-muted font-weight-bold' %>">
                <%= @user.status %>
              </td>
            </tr>
            <tr>
              <td><strong>会員ステータス<strong></td>
              <td class="<%= @user.is_active ? 'text-success font-weight-bold' : 'text-muted font-weight-bold' %>"><%= @user.is_active_status %></td>
            </tr>
            <tr>
              <td><strong>フォロー数</strong></td>
              <td><%= @user.followings.count %></td>
            </tr>
            <tr>
              <td><strong>フォロワー数</strong></td>
              <td><%= @user.followers.count %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-lg-8 col-md-12">
      <div class="card p-3 shadow-sm">
        <h5 class="font-weight-bold mb-4">旅行ログ</h5>
        <table class="table table-bordered table-hover">
          <thead class="thead-light">
            <tr>
              <th>タイトル</th>
              <th>旅行先</th>
              <th>投稿者</th>
              <th>評価</th>
              <th>コメント</th>
              <th>いいね</th>
            </tr>
          </thead>
          <tbody>
            <% @logs.each do |log| %>
              <tr>
                <td><%= link_to log.title, admin_log_path(log.id) %></td>
                <td><%= log.location %></td>
                <td><%= log.user.name %></td>
                <td><%= render "public/logs/static_rate", log: log %></td>
                <td><%= link_to "#{log.log_comments.count} コメント", admin_log_path(log.id) %></td>
                <td><%= link_to "#{log.favorites.count} いいね", admin_log_path(log.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="text-center my-4">
    <%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-success btn-lg" %>
  </div>
</div>