config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "users/unsubscribe" => "users#unsubscribe"
    patch "users/withdraw" => "users#withdraw"
    get '/search', to: 'searches#search'
    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :logs, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :log_comments, only: [:create, :destroy]
    end
  end
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :logs, only: [:index, :show, :destroy]
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LogTravel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <script src="https://kit.fontawesome.com/f1ce1e6c42.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100 ">
    <header class="border-bottom">
      <div class="container-fluid">
        <div class="row">
 
          <div class="col-md-4 text-center d-flex align-items-center">
            <a class="navbar-brand" href="/" style="font-family: 'Roboto', sans-serif; font-size: 2rem; font-weight: bold; color: #0066cc; letter-spacing: 2px; transition: transform 0.3s;">
              <i class="bi bi-airplane-engines" style="font-size: 2.5rem; color: #ff5733;"></i>
              <span class="ml-2">LogTravel</span>
            </a>
          </div>
          <style>
            .navbar-brand:hover {
              transform: scale(1.1); /* ホバー時にロゴを少し拡大 */
            }
          </style>

          <div class="col-md-2 text-center d-flex align-items-center">
            <% if user_signed_in? %>
              <strong class="w-100">ようこそ、<%= current_user.name%>さん!</strong>
            <%end%>
          </div>
          <div class="col-md-6">
            <div class="d-flex flex-column align-logs-end mt-3">
              <nav class="navbar navbar-expand-lg p-0">
                <ul class="nav">
                  <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to "マイページ", user_path(current_user), class: "nav-link btn btn-outline-secondary text-dark mx-3" %></li>
                    <li class="nav-item"><%= link_to "新規投稿", new_log_path, class: "nav-link btn btn-outline-secondary text-dark mx-3" %></li>
                    <li class="nav-item"><%= link_to "ログ一覧", logs_path, class: "nav-link btn btn-outline-secondary text-dark mx-3" %></li>
                    <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link btn btn-outline-secondary text-dark ml-3" %></li>
                  <% elsif admin_signed_in? %>
                    <li class="nav-item"><%= link_to "ログ一覧", admin_logs_path, class: "nav-link btn btn-outline-secondary text-dark mx-3" %></li>
                    <li class="nav-item"><%= link_to "ユーザー一覧", admin_users_path, class: "nav-link btn btn-outline-secondary text-dark mx-3" %></li>
                    <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link btn btn-outline-secondary text-dark ml-3" %></li>
                  <% else %>
                    <li class="nav-item"><%= link_to "Top", root_path, class: "nav-link btn btn-outline-secondary text-dark mx-3" %></li>
                    <li class="nav-item"><%= link_to "About", about_path, class: "nav-link btn btn-outline-secondary text-dark mx-3" %></li>
                    <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: "nav-link btn btn-outline-secondary text-dark mx-3" %></li>
                    <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: "nav-link btn btn-outline-secondary text-dark ml-3" %></li>
                  <% end %>
                </ul>
              </nav>
              <form class="form-inline mt-2 mb-3">
              </form>
            </div>
          </div>
        </div>
      </div>
    </header>
    <main class="mb-auto">
      <p class="mx-auto" id="notice"><%= notice %></p>
      <div class="container">
        <div class="row justify-content-end mb-2">
          <div class="mr-3"><%= render 'public/searches/form' %></div>
          <div class="mr-3"><%= render "public/searches/tag_form" %></div>
        </div>
      </div>
      <%= yield %>
    </main>

    <div class="mt-5"></div>
    <footer class="bg-dark text-white py-4 mt-auto">
      <div class="mt-3 text-center">
        <p>&copy; <%= Time.now.year %> LogTravel. All rights reserved.</p>
      </div>
    </footer>

  </body>
</html>